spring:
  application:
    name: account
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${DATASOURCE_SCHEMA_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ACCOUNT_JWT_ISSUER_URI}
          jwk-set-uri: ${ACCOUNT_JWT_JWK_SET_URI}
      client:
        registration:
          account-service-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${ACCOUNT_CLIENT_ID}
            client-secret: ${ACCOUNT_CLIENT_SECRET}
        provider:
          keycloak:
            token-uri: ${ACCOUNT_OAUTH2_TOKEN_URI}

server:
  port: ${SERVER_PORT}

integration:
  oauth2:
    registration-id: ${ACCOUNT_OUTBOUND_OAUTH2_REGISTRATION_ID}
  notification:
    base-url: ${NOTIFICATION_BASE_URL}

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      notificationService:
        maxAttempts: 3
        waitDuration: 300ms
