plugins {
    id 'org.springframework.boot' version '4.0.3' apply false
    id 'org.openapi.generator' version '7.20.0' apply false
}

def bootProjects = ['front', 'account', 'cash', 'transfer', 'notification']
def webProjects = ['front', 'account', 'cash', 'transfer']
def openApiProjects = ['front', 'account', 'cash', 'transfer']
def libraryProjects = ['common']

version = '0.0.1-SNAPSHOT'
description = 'my-bank-app'

allprojects {
    group = 'ru.practicum'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
        implementation.exclude module: 'spring-boot-starter-logging'
    }

    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok
    }
}

configure(subprojects.findAll { it.name in libraryProjects }) {
    apply plugin: 'java-library'
}

configure(subprojects.findAll { it.name in bootProjects }) {
    apply plugin: 'org.springframework.boot'
}

configure(subprojects.findAll { it.name in webProjects }) {
    dependencies {
        implementation libs.spring.boot.starter.webmvc
        implementation libs.spring.boot.starter.validation
        implementation libs.springdoc.openapi.starter.webmvc.ui

        testImplementation libs.spring.boot.starter.webmvc.test
    }
}

configure(subprojects.findAll { it.name in openApiProjects }) {
    apply plugin: 'org.openapi.generator'
}

configure(subprojects.findAll { it.name in bootProjects }) {
    dependencies {
        implementation libs.spring.boot.starter.actuator
        implementation libs.spring.boot.starter.log4j2

        implementation libs.micrometer.tracing.bridge.brave
        implementation libs.zipkin.reporter.brave
        implementation libs.micrometer.registry.prometheus
        implementation libs.log4j.layout.template.json

        testImplementation libs.spring.boot.starter.test
        testImplementation libs.spring.kafka.test
        testRuntimeOnly libs.junit.platform.launcher
    }

    tasks.named('test') {
        useJUnitPlatform()
        systemProperty 'spring.profiles.active', 'test'
        exclude '**/*IT.class'
    }

    tasks.register('integrationTest', Test) {
        description = 'Runs integration tests.'
        group = 'verification'
        useJUnitPlatform()
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
        include '**/*IT.class'
        systemProperty 'spring.profiles.active', 'test'
        shouldRunAfter tasks.test
    }
}
