spring:
  application:
    name: transfer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TRANSFER_JWT_ISSUER_URI}
          jwk-set-uri: ${TRANSFER_JWT_JWK_SET_URI}
      client:
        registration:
          transfer-service-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${TRANSFER_CLIENT_ID}
            client-secret: ${TRANSFER_CLIENT_SECRET}
        provider:
          keycloak:
            token-uri: ${TRANSFER_OAUTH2_TOKEN_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true

server:
  port: ${SERVER_PORT}

integration:
  oauth2:
    registration-id: ${TRANSFER_OUTBOUND_OAUTH2_REGISTRATION_ID}
  account:
    base-url: ${ACCOUNT_BASE_URL}
  notification:
    topic: ${NOTIFICATION_TOPIC:notification-events}

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      notificationService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 300ms
        ignoreExceptions:
          - ru.practicum.transfer.domain.exception.InvalidAmountException
          - ru.practicum.transfer.domain.exception.AccountNotFoundException
          - ru.practicum.transfer.domain.exception.InsufficientFundsException
      notificationService:
        maxAttempts: 3
        waitDuration: 300ms
