spring:
  config:
    import: "optional:consul:" # ?????????? Consul ??? ???????? ???????????? (??? ?????? ??? ????????? ?????????????)
  application:
    name: front
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost} #(localhost ??? ?????????? ???????, consul ??? Docker)
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true # ???????? ?????? ???????????? ?? Consul KV
        fail-fast: false # ?? ?????? ??????, ???? Consul ???????? ?????????? ??? ??????/??????
        prefixes:
          - config # ??????? ??????? KV: config/<context>/...
        format: YAML # ???????? ????? data ???????????????? ??? YAML
        data-key: data # ??? leaf-????? ? ???????? ????????? ????????????
        profile-separator: "," # ??????????? context ? profile (??????: gateway,default)
        watch:
          wait-time: 5 # Long-poll ???????? ?????? ?? Consul (???????)
          delay: 10000 # ???????? ????? ?????????? watch (????????????)

server:
  port: ${SERVER_PORT}
