spring:
  config:
    import: "optional:consul:" # Подключаем Consul как источник конфигурации (без фатала при временной недоступности)
  application:
    name: notification
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost} #(localhost для локального запуска, consul для Docker)
      port: ${CONSUL_PORT:8500}
      config:
        enabled: true # Включаем чтение конфигурации из Consul KV
        fail-fast: false # Не роняем сервис, если Consul временно недоступен при старте/чтении
        prefixes:
          - config # Базовый префикс KV: config/<context>/...
        format: YAML # Значение ключа data интерпретируется как YAML
        data-key: data # Имя leaf-ключа с полезной нагрузкой конфигурации
        profile-separator: "," # Разделитель context и profile (пример: gateway,default)
        watch:
          wait-time: 5 # Long-poll ожидание ответа от Consul (секунды)
          delay: 10000 # Интервал между итерациями watch (миллисекунды)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${NOTIFICATION_JWT_ISSUER_URI}

server:
  port: ${SERVER_PORT}
