spring:
  application:
    name: notification
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${NOTIFICATION_JWT_ISSUER_URI}
          jwk-set-uri: ${NOTIFICATION_JWT_JWK_SET_URI}

server:
  port: ${SERVER_PORT}
