apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "logstash.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "logstash.name" . }}
  ports:
    - name: beats
      port: {{ .Values.app.service.ports.beats }}
      targetPort: beats
      protocol: TCP
    - name: api
      port: {{ .Values.app.service.ports.api }}
      targetPort: api
      protocol: TCP
