apiVersion: v2
name: my-bank
description: Umbrella Helm chart for My Bank App on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: front
    version: 0.1.0
    repository: file://charts/front
  - name: account
    version: 0.1.0
    repository: file://charts/account
  - name: cash
    version: 0.1.0
    repository: file://charts/cash
  - name: transfer
    version: 0.1.0
    repository: file://charts/transfer
  - name: notification
    version: 0.1.0
    repository: file://charts/notification
  - name: postgresql
    version: "18.5.15"
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    version: "25.2.0"
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: "18.0.1"
    repository: https://helm-charts.itboon.top/kafka
  - name: zipkin
    version: "0.4.0"
    repository: https://zipkin.io/zipkin-helm
  - name: prometheus
    version: "28.7.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: "10.4.0"
    repository: https://grafana.github.io/helm-charts
  - name: elasticsearch
    version: "19.21.2"
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: logstash
    version: 0.1.0
    repository: file://charts/logstash
  - name: kibana
    version: "12.1.10"
    repository: oci://registry-1.docker.io/bitnamicharts
