front:
  secretEnv:
    FRONT_CLIENT_SECRET: front-secret

account:
  secretEnv:
    SPRING_DATASOURCE_PASSWORD: postgres
    ACCOUNT_CLIENT_SECRET: account-secret

cash:
  secretEnv:
    CASH_CLIENT_SECRET: cash-secret

transfer:
  secretEnv:
    TRANSFER_CLIENT_SECRET: transfer-secret

notification:
  secretEnv: {}

postgresql:
  auth:
    password: postgres
    postgresPassword: postgres

keycloak:
  auth:
    adminPassword: admin
  externalDatabase:
    password: postgres
