front:
  app:
    secretEnv:
      FRONT_CLIENT_SECRET: front-secret

account:
  app:
    secretEnv:
      SPRING_DATASOURCE_PASSWORD: postgres

cash:
  app:
    secretEnv:
      CASH_CLIENT_SECRET: cash-secret

transfer:
  app:
    secretEnv:
      SPRING_DATASOURCE_PASSWORD: postgres
      TRANSFER_CLIENT_SECRET: transfer-secret

notification:
  app:
    secretEnv:
      SPRING_DATASOURCE_PASSWORD: postgres

postgresql:
  auth:
    password: postgres
    postgresPassword: postgres

keycloak:
  auth:
    adminPassword: admin
  externalDatabase:
    password: postgres
