app:
  nameOverride: cash

  replicaCount: 1

  image:
    repository: cash-app
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8083

  env: {}
  secretEnv: {}

  probes:
    startup:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 60
    readiness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 6
    liveness:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 6

  resources: {}
