input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }

  mutate {
    add_field => {
      "[event][dataset]" => "bank.application"
    }
  }

  if [message] {
    mutate {
      gsub => [
        "message", "(?i)(password=)([^\\s,;]+)", "\\1***",
        "message", "(?i)(token=)([^\\s,;]+)", "\\1***",
        "message", "(?i)(bearer\\s+)([^\\s,;]+)", "\\1***"
      ]
    }
  }

  if [exception] {
    mutate {
      gsub => [
        "exception", "(?i)(password=)([^\\s,;]+)", "\\1***",
        "exception", "(?i)(token=)([^\\s,;]+)", "\\1***",
        "exception", "(?i)(bearer\\s+)([^\\s,;]+)", "\\1***"
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bank-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
