version = '0.0.1'
description = 'common'

dependencies {
    implementation libs.spring.boot.autoconfigure
    implementation libs.spring.webmvc
    implementation libs.spring.security.oauth2.client
    implementation libs.jackson.databind

    compileOnly libs.jakarta.servlet.api
    compileOnly libs.slf4j.api
    compileOnly libs.log4j.api
    compileOnly libs.micrometer.tracing
}
