app:
  nameOverride: transfer

  replicaCount: 1

  image:
    repository: transfer-app
    tag: 1.2.0
    pullPolicy: IfNotPresent

  service:
    port: 8084

  env: {}
  secretEnv: {}

  probes:
    startup:
      enabled: true
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 60
    readiness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 6
    liveness:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 6

  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 384Mi
